# Generated by Django 2.2.7 on 2019-11-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='brand',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
