# Generated by Django 2.2.7 on 2019-11-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken', '0003_chicken_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='image',
            field=models.ImageField(default='images/default_image.PNG', upload_to=''),
        ),
    ]
