# Generated by Django 2.2.7 on 2019-11-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken', '0004_auto_20191105_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='image',
            field=models.ImageField(default='default_image.PNG', upload_to=''),
        ),
    ]
